#!/usr/bin/with-contenv bash
set -e

CRON=${CRON:-'*/15 * * * *'}

if [ -n "${CRON}" ]; then
    echo "Configure docker-runner-clean @ ${CRON}"
    echo "${CRON}    /usr/local/bin/docker-runner-clean" > /etc/crontabs/root
fi

# EOF